### ISSUE TITLE
Implement Default state when Projecter is without Power

### ISSUE THREAD

**Issue by lord-drinkalot** [bezmi/homeassistant_jvc_projector_remote#13]
When the Projector is powered off and I reset my HA Instance, the Integration fails to start.
And I cannot get it to work without powering on the PJ and resetting HA.

Maybe implement a ping if the IP is reachable, if not update with a "not connected" state and skip the rest.
![image](https://user-images.githubusercontent.com/16001421/180439460-c7a189b4-9ca2-4e59-8e3a-52dd4e40f981.png)

`Log Details (ERROR)
Logger: homeassistant.components.remote
Source: custom_components/jvcprojector/remote.py:62
Integration: Remote ([documentation](https://www.home-assistant.io/integrations/remote), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+remote%22))
First occurred: 14:11:39 (1 occurrences)
Last logged: 14:11:39

Error while setting up jvcprojector platform for remote
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 79, in __connect
    jvc_sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 59, in __init__
    self._send_command(Commands.nullcmd)
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 149, in _send_command
    jvc_sock: socket.socket = self.__handshake()
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 106, in __handshake
    jvc_sock = self.__connect()
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 93, in __connect
    jvc_sock = self.__connect(retry + 1)
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 93, in __connect
    jvc_sock = self.__connect(retry + 1)
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 93, in __connect
    jvc_sock = self.__connect(retry + 1)
  [Previous line repeated 8 more times]
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 96, in __connect
    raise JVCCannotConnectError(
jvc_projector_remote.jvccommands.JVCCannotConnectError: Could not establish connection to projector

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/jvcprojector/remote.py", line 36, in setup_platform
    JVCRemote(name, host, password, port, delay, timeout, retries),
  File "/config/custom_components/jvcprojector/remote.py", line 62, in __init__
    self._jvc = JVCProjector(host, password, port, delay, timeout, retries)
  File "/usr/local/lib/python3.10/site-packages/jvc_projector_remote/jvcprojector.py", line 61, in __init__
    raise JVCConfigError(
jvc_projector_remote.jvccommands.JVCConfigError: Couldn't verify connection to projector at the specified address: 192.168.1.49:20554. Make sure the host and port are set correctly and control4 is turned off in projector settings`

**Comment by lord-drinkalot** [comment]
Correct, no Power at all, I use a APC PDU and control it with SNMP.
So If I don't watch something, the outlet is disabled and the PJ is not in Standby.

If the PJ is in Standby then everything works as expected.

**Comment by bezmi** [comment]
This should work now.
